version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT:-5432}/${DB_NAME:-springboot_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-postgres}
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE:-dev}
      - SECURITY_JWT_SECRET=${JWT_SECRET:-5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
      - SECURITY_JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - LOGGING_LEVEL_ROOT=${LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_COM_SHOPDEVJAVA_SPRINGBOOT=${LOG_LEVEL:-INFO}
    depends_on:
      - db
    networks:
      - spring-postgres

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-springboot_db}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  postgres-data:

networks:
  spring-postgres:
    driver: bridge 